import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="flex  ">
        <ClerkProvider>
          <div className="flex flex-row">
            <Sidebar />
            <main className="flex-1 p-8 bg-gray-50 ml-[14vw] min-h-screen min-w-screen ">{children}</main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}